enum EUserAction {
  FETCH_USERS = "[USERS] FETCH_USERS",
  FETCH_USERS_SUCCESS = "[USERS] FETCH_USERS_SUCCESS",
  SET_USER = "[USERS] SET_USER",
  ADD_USER = "[USERS] ADD_USER",
  DELETE_USER = "[USERS] DELETE_USER",
  UPDATE_USER = "[USERS] UPDATE_USER",
}
export default EUserAction;
