enum ECommonAction {
  UPDATE_LOADDING = "[COMMON] UPDATE_LOADDING",
  FETCH_CONFIG = "[COMMON] FETCH_CONFIG",
  FETCH_CONFIG_SUCCESS = "[COMMON] FETCH_CONFIG_SUCCESS",
}
export default ECommonAction;
