enum ECommonAction {
  UPDATE_LOADING = "[COMMON] UPDATE_LOADING",
  FETCH_CONFIG = "[COMMON] FETCH_CONFIG",
  FETCH_CONFIG_SUCCESS = "[COMMON] FETCH_CONFIG_SUCCESS",
  OPEN_NOTIFICATION = "[COMMON] OPEN_NOTIFICATION",
}
export default ECommonAction;
